---
apiVersion: v1
kind: Secret
metadata:
  name: fib-infra
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/jkulzer/fib-infra.git
