apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fib-backend
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: backend
    repoURL: https://github.com/jkulzer/fib-infra
